### PR TITLE
Updated install documentation

### PR DESCRIPTION
**Pull request by clintonskitson**
This commit updates the documentationt to better describe how to
properly install REX-Ray manually. It also has some general
information updates.

### CODE REVIEW

**Comment by clintonskitson** [comment]
Will rebase this with new RC6 branch.

**Comment by clintonskitson** [comment]
Rebased

**Comment by akutz** [comment]
Hi @clintonskitson,

I'm closing this PR. Please reopen it against `release/0.3.2`. It's currently open against `master`, hence the commit diffs.

**Comment by akutz** [comment]
Hi @clintonskitson,

And when you do recreate it, please rebase again since I've also merged in the CoreOS fix.

**Pull request closed without merging**
