### PR TITLE
Feature/doc updates

### PR DESCRIPTION
**Pull request by clintonskitson**
This PR is a consolidation of doc updates that are intended for the 0.3.1 release.  There is still work that needs to be done here for each commit but it is a good start.  Not intending to merge this as is.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @clintonskitson,

Are you satisfied with this PR's content? You said you don't wish to merge as is, but I wasn't sure if the cause was lack of content or some other reason. If it's to clean up the commits I can do that when I have a moment. Just let me know.

**Comment by clintonskitson** [comment]
Some of the commits in here are unfinished.  I will submit other PRs that would include discrete section updates.

**Comment by clintonskitson** [comment]
I am good with these doc updates.

**Comment by akutz** [comment]
Hi @kacole2, @dvonthenen, @drumulonimbus,

Your doc updates look great, but before we can accept them we need you to limit your lines to 80 chars per all of the other markdown files in the docs section. This is a standard to which we adhere to make the sources more readable and to make writers consider brevity always. @kacole2, you do a fantastic job with brevity, so thank you. It's just that we want hard line breaks to boot. Thanks all.

**Comment by clintonskitson** [comment]
Looks good to me now.

**Pull request merged**
