### PR TITLE
Foundation Improvements Part Deux

### PR DESCRIPTION
**Pull request by akutz**
This path refactors REX-Ray to reduce the top-level elements as well as introduce the notion of `RexRay` platform. To use REX-Ray all that's now required is:

    import "github.com/emccode/rexray"

    r := rexray.New()

### CODE REVIEW

**Comment by akutz** [comment]
Hi @clintonskitson,

I'll be relying on you to do the manual testing to provide proof that this doesn't break existing functionality.

**Comment by clintonskitson** [comment]
Ok, will run it across all of the drivers.

**Comment by clintonskitson** [comment]
Just noticed missing `_ "github.com/emccode/rexray/drivers/storage/openstack"` in `/drivers/storage.go`

**Comment by akutz** [comment]
Add it locally and I'll add it in the PR in a bit

-- 
-a

**Comment by clintonskitson** [comment]
https://github.com/akutz/rexray/pull/1

**Pull request merged**
