### PR TITLE
Added ec2 tags to volumes and snapshots (Updated for release-0.3.3)

### PR DESCRIPTION
**Pull request by echupriyanov**
Updated PR against `release-0.3.3` branch

Signed-off-by: Eugene Chupriyanov <tchu@tchu.ru>

### CODE REVIEW

**Comment by clintonskitson** [comment]
Waiting on merge of https://github.com/emccode/rexray/pull/359

**Comment by miry** [comment]
@echupriyanov You can add only 1 tag as I understand, the tag key name is static to `rexraySet`. Correct?

Is it possible to specify custom key/value tags ?

**Comment by echupriyanov** [comment]
@miry Yes. In this PR tag is hard-coded to be `rexraySet`.
But, since this PR is going to be rewritten based on official AWS SDK, I’m open for suggestions on how to improve it.

Custom tag keys/values is a good idea. I’ll think how to implement it.

**Comment by akutz** [comment]
Hi @echupriyanov,

I'd love to merge this for 0.3.3, but you'll need to rebase this off of 0.3.3 to incorporate your ec2 SDK changes. I started to merge it myself, but I ran into enough compile issues that I decided to "delegate" it back to you :)

**Comment by akutz** [comment]
Hi @echupriyanov / @clintonskitson,

I went ahead and created a [merge branch](https://github.com/emccode/rexray/compare/release/0.3.3...akutz:echupriyanov-ec2tags-0.3.3?expand=1) with the above changes. If you want, you can just update your PR branch to reflect the linked patch.

**Comment by akutz** [comment]
Hi @echupriyanov / @clintonskitson,

I merged this so we can push a 0.3.3-RC1 sooner than later. If there are issues with it we can revert it.

**Comment by echupriyanov** [comment]
@akutz sorry, was offline this weekend and didn’t help you to prepare PR. Hope to be more useful next time.

**Comment by clintonskitson** [comment]
@echupriyanov Could do test RC1 with your changes?

**Comment by echupriyanov** [comment]
@clintonskitson sure. I plan to build testing swarm cluster tomorrow, and will install RC1 on it.

**Comment by akutz** [comment]
Hi @echupriyanov, no worries! Thank you so much for the initial work on this and the other branch. Just at a glance though does this look like I captured your changes correctly?

**Pull request merged**
