### PR TITLE
Feature/gce driver

### PR DESCRIPTION
**Pull request by clintonskitson**
This PR includes a working GCE driver.  Will look to update this PR when pre-emption is merged.

### CODE REVIEW

**Comment by clintonskitson** [comment]
Nice job @ltouati.  All tests are passing, and we will figure out when to merge this shortly.

**Comment by ltouati** [comment]
ok great thanks a lot

**Comment by clintonskitson** [comment]
@akutz I believe we are good here now with pre-emption support.

**Comment by clintonskitson** [comment]
Driver now is fully functional including snapshots.

**Comment by akutz** [comment]
This PR will not be merged until @clintonkitson's previous comment is updated with appropriate meme. 
image

**Comment by akutz** [comment]
This cannot be merged until @clintonskitson updates his previous comment with the contextual and appropriate meme. 
image

**Pull request merged**
