### PR TITLE
Updating Instructions on How to get REX-Ray

### PR DESCRIPTION
**Pull request by akutz**
This patch updates the README with instructions on how to install, download, and build REX-Ray. @clintonskitson, please review the [updated README](https://github.com/akutz/rexray/tree/feature/getting-rexray-updates) and provide feedback and/or merge this PR. Thanks!

### CODE REVIEW

**Comment by akutz** [comment]
Hi @kacole2,

Do you also mind taking a look at the [README updates](https://github.com/akutz/rexray/tree/feature/getting-rexray-updates)? Thank you.

**Comment by kacole2** [comment]
the README is a bit bloated, we will tackle that at some point. We could have a `developer.md` that talks how to build from source as well as all the intricacies. but for now it LGTM

**Comment by akutz** [comment]
Hi @kacole2,

Thank you for your overall estimate, and yes, when I have time I will tackle the README. Or, you know, anyone can do it by filing a PR. But for now what I asked is for a review of the changes only per the commit and represented visually on the branch. Specifically it's the `Installation`, `Downloading`, and `Building` sections to which I'm referring. I'll agree with bloat, but all OSS projects worth a damn have how to build from source on the front-page and then go into advanced detail elsewhere. That aside, please provide feedback on the formatting and content of the requested sections. Thank you.

**Comment by kacole2** [comment]
LGTM

**Comment by akutz** [comment]
Hi @kacole2,

Oh. I thought that was LMGTFY with regards to build instructions and were telling devs to "Google it" as opposed to put it in the documentation. My nights are long followed by equally long days, my eyes are dead by 3pm my time it seems. Thank you.

**Pull request merged**
