### PR TITLE
added yaml example config file

### PR DESCRIPTION
**Pull request by clintonskitson**
This patch adds an example config yaml file.

### CODE REVIEW

**Comment by clintonskitson** [comment]
Referencing issue https://github.com/emccode/rexray/issues/43

**Comment by akutz** [comment]
Hi @clintonskitson,

I'd like to close this PR without accepting it so I can create a default config file that includes all of the default options as well as commented out provider options with explanations. Thoughts?

**Comment by kacole2** [comment]
one thing to add is to please note where the `config.yml` file needs to be dropped so RR can read it. or note if it must be referenced during `sudo rexray service start`

thanks gents

**Comment by akutz** [comment]
Hi @kacole2,

The command already shows one place:

```
REX-Ray:
  A guest-based storage introspection tool that enables local
  visibility and management from cloud and storage platforms.

Usage: 
  rexray [flags]
  rexray [command]

Available Commands: 
  volume      The volume manager
  snapshot    The snapshot manager
  device      The device manager
  adapter     The adapter manager
  service     The service controller
  version     Print the version
  help        Help about any command

Global Flags:
  -c, --config="/home/akutz/.rexray/config.yaml": The REX-Ray configuration file
  -?, --help[=false]: Help for rexray
  -h, --host="tcp://:7979": The REX-Ray service address
  -l, --logLevel="info": The log level (panic, fatal, error, warn, info, debug)
  -v, --verbose[=false]: Print verbose help information

Use "rexray [command] --help" for more information about a command.
```

However, I'll update the docs to reflect the official locations. FWIW, anyone can open a PR and update the docs. :)

**Comment by kacole2** [comment]
thanks... i didn't notice that. 

as for the hidden directory `/home/akutz/.rexray/`, was that created during `sudo rexray service install`? Just curious because I will need to retrieve the home path for the current user and append that folder for the docker-machine process.

**Comment by akutz** [comment]
Hi @kacole2,

It doesn't exist. The rule is that the config file is parsed first from $HOME/.rexray/config.yaml if it exists and then /etc/rexray/config.yaml if that exists. Otherwise it doesn't use a config file unless one is specified on the command line with the flag you see above.

**Comment by kacole2** [comment]
Perfect.  Thanks

**Comment by clintonskitson** [comment]
I'm good with that @akutz

**Pull request closed without merging**
