### PR TITLE
Implemented Isilon Snapshots

### PR DESCRIPTION
**Pull request by danforrest**
* Implemented GetSnapshot, CreateSnapshot and RemoveSnapshot
* Updated documentation

### CODE REVIEW

**Comment by danforrest** [comment]
This PR also contains changes from the feature/isilon_size_and_preemption PR because the snapshots needed to use some of its size functionality.

NOTE: To test snapshots, you'll need to enable a SnapshotIQ license and add the privilege ISI_PRIV_SNAPSHOT to your test role.

**Comment by clintonskitson** [comment]
@akutz Let's reach out to @danforrest when the https://github.com/emccode/rexray/pull/231 is merged so he can redo this commit.

**Comment by clintonskitson** [comment]
Testing wise this one is on hold until I can get a temporary license key.  Open opportunity to include in RC2 if it misses the cut today.

**Comment by danforrest** [comment]
Rebased off of 0.3.2-rc1.

**Comment by clintonskitson** [comment]
@danforrest It looks like the `volumeSize` is being sent back in bytes instead of GB.

`volumesize: "17179869184"`

**Comment by clintonskitson** [comment]
@danforrest One of the features is to create a new volume from an existing snapshot.  Is that going to be  possible?

This should be possible by specifying `snapshotid` or `volumeid`.  I am currently getting the following error.  Guessing that the existing size needs to be queried when submitting this for the new volume?  Actually not really sure what the feature would be used for without this working other than just PIT copies that can be used from outside of RR.

```
[root@localhost temp]# ./rexray volume create --volumename=data4-newvol --snapshotid=data4-snap1
FATA[0000] Error setting quota for new volume            inner=Field: thresholds.hard has error: The value must be greater than or equal to 1. provider=Isilon volumeName=data4-newvol
```

**Comment by clintonskitson** [comment]
Just noticed that you can specify `size` along with it, but I believe this should default to using size from snap/volume.

**Comment by clintonskitson** [comment]
The request to create a volume from an existing volume isn't working as expected.  This is just returning the existing `volumeid` versus a new one with the anem of `data4-newvol3`.  `./rexray volume create --volumeid=data4-newvol --volumename=data4-newvol3 --size=8`

**Comment by clintonskitson** [comment]
Creating a volume from the snapshot returns a blank directory.

```
[root@localhost temp]# ./rexray snapshot create --snapshotname=data4-newvol-snap2 --volumeid=data4-newvol
[root@localhost temp]# ./rexray volume create --volumename=data4-newvol4 --snapshotid=data4-newvol-snap2 --size=8
```

**Comment by clintonskitson** [comment]
Still waiting for @danforrest on this one.

**Comment by danforrest** [comment]
Fixed size units.  Added feature to create volume from another volume or a snapshot.

**Comment by danforrest** [comment]
Found one more spot where the volume size was in the wrong units that I missed earlier.

**Comment by clintonskitson** [comment]
@danforrest Two problems I ran into. 

Can't create a volume from a snapshot for some reason.
```
[root@localhost rc1]# /home/temp/rexray snapshot ls --volumeid=testing62
- name: testing62-snap1
  volumeid: testing62
  snapshotid: "10"
  volumesize: "16"
  starttime: "1453698872"
  description: ""
  status: active

[root@localhost rc1]# /home/temp/rexray volume create --volumename=testing62-copy2 --snapshotid=testing62-snap1
FATA[0000] Error creating volume                         inner=Unable to open object '/.snapshot/testing62-snap1/volumes/testing62/' in store 'ifs' -- not found. provider=Isilon volumeName=testing62-copy2
```

Still needed to specify size manually.
```
[root@localhost rc1]# /home/temp/rexray volume create --volumeid=testing62 --volumename=testing62-copy
FATA[0000] Error setting quota for new volume            inner=Field: thresholds.hard has error: The value must be greater than or equal to 1. provider=Isilon volumeName=testing62-copy
[root@localhost rc1]# /home/temp/rexray volume create --volumeid=testing62 --volumename=testing62-copy --size=10
```

**Comment by danforrest** [comment]
Can you send me a directory listing (from the Isilon cluster) of /ifs/.snapshot and /ifs/.snapshot/testing62-snap1/volumes

**Comment by clintonskitson** [comment]
```
testing-1% ls /ifs/.snapshot 
data4-newvol-snap1	data4-newvol-snap2	data4-snap1		testing62-snap1
testing-1% ls /ifs/.snapshot/testing62-snap1/volumes
rexray
testing-1% 

```

**Comment by clintonskitson** [comment]
@danforrest Will review this shortly.

**Comment by danforrest** [comment]
I wasn't handling the volumePath correctly.  It should work now.  Also, when creating a volume from another volume or snapshot, it should use the size of the existing volume/snapshot.

**Comment by danforrest** [comment]
What do I need to do to take care of the coverage check?  I haven't had to do anything with the REX-Ray tests before this.

**Comment by clintonskitson** [comment]
No change will be fine.

**Comment by danforrest** [comment]
Ok, sounds good.

**Comment by clintonskitson** [comment]
@akutz This tests good from my end.
@dannforrest Well done!

**Pull request merged**
