### PR TITLE
CoreOS/SystemD Service Start Fix

### PR DESCRIPTION
**Pull request by akutz**
This patch is a fix for issue #326, where CoreOS is placing SSH sessions into a CGroup, thus killing any REX-Ray daemons not specifically launched via SystemD.

This patch actually adjusts REX-Ray's behavior for not just CoreOS systems, but any Linux using SystemD. All SystemD-based systems now prefer SystemD for service-control-management (SCM) commands.

### 1. Verifying the version
```
core@CoreOS ~ $ rexray version
Binary: /opt/bin/rexray
SemVer: 0.3.2-rc5+2+dirty
OsArch: Linux-x86_64
Branch: bugfix/coreos-start-service
Commit: 13be71f6ad962f859bc5b284f18bf69179954737
Formed: Wed, 02 Mar 2016 12:26:23 UTC
```

### 2. Become the `root` user
```
core@CoreOS ~ $ sudo su -
```

### 3. Starting REX-Ray via `rexray start` as `root`
```
CoreOS ~ # env REXRAY_MOCKDRIVERS=true REXRAY_STORAGEDRIVERS=mockStorageDriver rexray start 
● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-03-02 12:43:43 UTC; 9ms ago
 Main PID: 754 (rexray)
   Memory: 1.7M
      CPU: 5ms
   CGroup: /system.slice/rexray.service
           └─754 /opt/bin/rexray start -f

Mar 02 12:43:43 CoreOS systemd[1]: Started rexray.
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=debug msg="updated log level" logLevel=debug
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=debug msg="invoking service start" os.Args=[/opt/bin/rexray start -f]
```

### 4. Dropping to a normal user session on CoreOS
```
CoreOS ~ # exit
logout
```

### 5. Checking the status of REX-Ray via `rexray status` as a normal user
``` 
core@CoreOS ~ $ rexray status
● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-03-02 12:43:43 UTC; 6s ago
 Main PID: 754 (rexray)
   Memory: 4.1M
      CPU: 16ms
   CGroup: /system.slice/rexray.service
           └─754 /opt/bin/rexray start -f

Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg="os driver initialized" moduleName=default-docker provider=linux
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=debug msg="checking volume path cache setting" pathCache=true
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg=vdm.List driverName=docker moduleName=default-docker
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg="listing volumes" driverName=docker moduleName=default-docker
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg=sdm.GetVolume driverName=mockStorageDriver moduleName=default-docker volumeID= volumeName=
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg=odm.GetMounts deviceName= driverName=linux moduleName=default-docker mountPoint=
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=debug msg="docker voldriver spec file" path="/etc/docker/plugins/rexray.spec"
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg="started module" address="unix:///run/docker/plugins/rexray.sock" name=default-docker typeName=docker
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg="service sent registered modules start signals"
Mar 02 12:43:43 CoreOS rexray[754]: time="2016-03-02T12:43:43Z" level=info msg="service successfully initialized, waiting on stop signal"
```

### 6. Verifying REX-Ray's PID
```
core@CoreOS ~ $ ps alx | grep rexray
4     0   754     1  20   0  42592 20892 futex_ Ssl  ?          0:00 /opt/bin/rexray start -f
0   500   775   739  20   0   6740   796 pipe_w S+   pts/0      0:00 grep --colour=auto rexray
```

### 7. Exiting the SSH session to CoreOS
```
core@CoreOS ~ $ exit
logout

Connection to 192.168.120.17 closed.
[0]akutz@pax:rexray$ 
```

### 8. Reconnecting to CoreOS via SSH and verifying REX-Ray is still running
```
[0]akutz@pax:rexray$ ssh coreos
Last login: Wed Mar  2 12:43:36 2016 from 192.168.120.3
CoreOS stable (835.13.0)
core@CoreOS ~ $ ps alx | grep rexray
4     0   754     1  20   0  42592 20892 futex_ Ssl  ?          0:00 /opt/bin/rexray start -f
0   500   811   807  20   0   6740   912 pipe_w S+   pts/0      0:00 grep --colour=auto rexray
core@CoreOS ~ $ 
```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @clintonskitson,

I'm assigning this to you for testing. I validated it on CoreOS (SystemD) and CentOS 7 (SystemD) to verify that REX-Ray now uses SystemD for starting, stopping, and checking the service status. I then verified that on Ubuntu 12.04 (SystemV) REX-Ray still does things the old way for SCM commands.

**Comment by akutz** [comment]
Hi @clintonskitson,

You can file your PR for the doc fix to add to this PR if you like. That way both changes are documented in a single PR.

**Comment by clintonskitson** [comment]
Ok, testing now.

**Comment by clintonskitson** [comment]
@akutz This tests out good for me, great job. I have another doc PR which is a bit broader so I think it makes sense to file it separately. I can move it here if you disagree.

**Comment by akutz** [comment]
Hi @clintonskitson,

I only mentioned collapsing the commits into this PR because when I checked this morning I did not see your PR listed. I'm sure it's fine separately as well. I'm going to first create a PR bumping the release train to RC6 for active dev, and then I'll merge this.

**Pull request merged**
