### PR TITLE
Updated to use ScaleIO v2 API

### PR DESCRIPTION
**Pull request by clintonskitson**
This commit adds the ability to integrate against ScaleIO v2
platforms.

### CODE REVIEW

**Comment by clintonskitson** [comment]
Considering changes in 0.4, this is just a placeholder for those needing v2 support in the short term.

**Comment by akutz** [comment]
Hi @clintonskitson,

If you want to supply a RR 0.3.3 for SIO2 support (a move for which I'm in favor), then please close this PR or rebase its commit so that the commit is created from the tag `v0.3.2`. For example:

```
$ git checkout -b feature/scaleio2-support v0.3.2
$ git cherry-pick 4545776
```

**Comment by clintonskitson** [comment]
@akutz Ok, did it to give us the option. I did that within the same branch, problem?

**Comment by clintonskitson** [comment]
Thanks @osskoss @kaleo211 on the emccode/goscaleio work.

**Comment by clintonskitson** [comment]
Addressing in 0.3.3 branch https://github.com/emccode/rexray/pull/355

**Pull request closed without merging**
