### PR TITLE
Update REX-Ray Builds to use Gomk

### PR DESCRIPTION
**Pull request by akutz**
This patch updates the REX-Ray build system to use Gomk. 

This patch should **NOT** be accepted/merged into master yet.

### CODE REVIEW

**Comment by clintonskitson** [comment]
Might be premature, but I gave this a shot.

```
make build-all
/Users/clintonkitson/go/bin/env-gnix GOOS=darwin GOARCH=amd64 /Applications/Xcode.app/Contents/Developer/usr/bin/make build
make: /Users/clintonkitson/go/bin/env-gnix: No such file or directory
make: *** [build-darwin_amd64] Error 1
```

**Comment by akutz** [comment]
Run 'make deps' first as a different make process altogether. You can't run make deps with build-all. Won't work. Or just run 'make', 'make install', or 'make build'

**Comment by akutz** [comment]
The build fails on Travis because the test coverage reports an error since I haven't updated the test package to cover the same packages it does via the test.sh script. That shouldn't prevent a build locally though. Heck, tests work too. It's just that the coverage command produces an empty output file since it isn't told what to cover.

**Comment by akutz** [comment]
Hi @clintonskitson,

`make build-all` should work fine now without needing to execute `make deps` first. Care to give it a try?

**Comment by clintonskitson** [comment]
Will do shortly thanks.

**Comment by clintonskitson** [comment]
@akutz So I was able to build it just fine but am not seeing the binary.  Is this just an initial integration?  Was missing the build-linux-amd64 part.  Caching looks to work.

**Comment by akutz** [comment]
Hi @clintonskitson,

Did you do a `make build-all`, `make` (an implied `make install`), or `make install-all`? Any variation of a build will place packages in `.gomk/tmp/build/pkg/$GOOS_$GOARCH` and binaries in `.gomk/tmp/build/bin/$GOOS_$GOARCH/`.

**Comment by akutz** [comment]
Hi @clintonskitson,

I just checked in a fix. I realized that the `rexray` binary wouldn't be properly cached upon build since it would exist at the same path as a folder with the same name. I've separated things out into the `pkg` and `bin` dirs as described in my last comment.

**Comment by clintonskitson** [comment]
Ok, got it this time.  The binary showed up in `.gomk/tmp/build/bin/linux_amd64/rexray` and I had to remove the old one to get a new copy.

Noticed the `rexray version` is as follows.  Service starts so looking good there.

```
DEBU[0000] updated log level                             logLevel=debug
Binary: /home/docker/rexray
SemVer: 
OsArch: 
Branch: 
Commit: 
Formed: 
```

**Comment by akutz** [comment]
Hi @clintonskitson,

I haven't added the Version bits to the new system yet; thanks for the reminder. As for the other thing about removing the old version, that's something to which you'll need to become accustom. It's how builds with Make work -- if dependencies have not changed, things are not rebuilt. Watch this:

```
[0]akutz@pax:rexray$ make build
go build  -o .gomk/tmp/build/bin/darwin_amd64/rexray ./rexray
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/rexray/cli.a ./rexray/cli
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/util.a ./util
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/test.a ./test
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray.a .
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/core.a ./core
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/core/version.a ./core/version
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/core/errors.a ./core/errors
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon.a ./daemon
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module.a ./daemon/module
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module/admin.a ./daemon/module/admin
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module/docker/remotevolumedriver.a ./daemon/module/docker/remotevolumedriver
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module/docker/volumedriver.a ./daemon/module/docker/volumedriver
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers.a ./drivers
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/mock.a ./drivers/mock
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/os.a ./drivers/os
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/os/linux.a ./drivers/os/linux
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage.a ./drivers/storage
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/ec2.a ./drivers/storage/ec2
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/gce.a ./drivers/storage/gce
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/isilon.a ./drivers/storage/isilon
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/openstack.a ./drivers/storage/openstack
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/rackspace.a ./drivers/storage/rackspace
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/scaleio.a ./drivers/storage/scaleio
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/virtualbox.a ./drivers/storage/virtualbox
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/vmax.a ./drivers/storage/vmax
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/xtremio.a ./drivers/storage/xtremio
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/volume.a ./drivers/volume
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/volume/docker.a ./drivers/volume/docker
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/rexray/cli/term.a ./rexray/cli/term
[0]akutz@pax:rexray$ make build
make: Nothing to be done for 'build'.
[0]akutz@pax:rexray$ touch rexray/rexray.go 
[0]akutz@pax:rexray$ make build
go build  -o .gomk/tmp/build/bin/darwin_amd64/rexray ./rexray
[0]akutz@pax:rexray$ 
```

Notice how the rexray binary was only rebuilt after the file `rexray/rexray.go` was touched (or changed)?

**Comment by akutz** [comment]
Hi @clintonskitson,

FYI, you'll need to pull the latest update. I noticed my packages/binaries were not rebuilding even after touching the files, and that's it occurred to me it was because I had disabled all the source tools for REX-Ray (see config.mk) to get past errors. Unfortunately the Make targets depended on the tool markers (which depend on the sources), and with no tools being executed, the dependency chain was broken. The package/binary targets now directly depend upon their related sources as well.

**Comment by akutz** [comment]
Hi @clintonskitson,

I just updated the PR so that version is included:

```
[0]akutz@pax:rexray$ make build
gofmt -w rexray.go
gofmt -w core/drivers_os.go
gofmt -w core/drivers_volume.go
gofmt -w core/drivers_storage.go
gofmt -w core/drivers.go
gofmt -w core/core.go
gofmt -w core/rexray.go
gofmt -w core/errors/errors.go
gofmt -w core/version/version.go
gofmt -w daemon/daemon.go
gofmt -w daemon/daemon_modules.go
gofmt -w daemon/module/module.go
gofmt -w daemon/module/admin/admin-scripts.go
gofmt -w daemon/module/admin/admin.go
gofmt -w daemon/module/admin/admin-images.go
gofmt -w daemon/module/admin/admin-styles.go
gofmt -w daemon/module/docker/remotevolumedriver/remvoldriver.go
gofmt -w daemon/module/admin/admin-html.go
gofmt -w daemon/module/docker/remotevolumedriver/notests.go
gofmt -w daemon/module/docker/volumedriver/voldriver.go
gofmt -w drivers/drivers.go
gofmt -w drivers/mock/mock_storage_driver.go
gofmt -w drivers/mock/mock_volume_driver.go
gofmt -w drivers/mock/mock.go
gofmt -w drivers/mock/mock_os_driver.go
gofmt -w drivers/os/os.go
gofmt -w drivers/os/linux/linux.go
gofmt -w drivers/storage/storage.go
gofmt -w drivers/storage/ec2/ec2.go
gofmt -w drivers/storage/gce/gce.go
gofmt -w drivers/storage/isilon/isilon.go
gofmt -w drivers/storage/openstack/openstack.go
gofmt -w drivers/storage/rackspace/rackspace.go
gofmt -w drivers/storage/scaleio/scaleio.go
gofmt -w drivers/storage/virtualbox/virtualbox.go
gofmt -w drivers/storage/vmax/vmax.go
gofmt -w drivers/storage/xtremio/xtremio.go
gofmt -w drivers/volume/volume.go
gofmt -w drivers/volume/docker/volume.go
gofmt -w rexray/rexray.go
gofmt -w rexray/cli/cmds_snapshot.go
gofmt -w rexray/cli/installer.go
gofmt -w rexray/cli/usage.go
gofmt -w rexray/cli/service_windows.go
gofmt -w rexray/cli/cmds_volume.go
gofmt -w rexray/cli/service.go
gofmt -w rexray/cli/cmds_module.go
gofmt -w rexray/cli/cmds_adapter.go
gofmt -w rexray/cli/cmds_other.go
gofmt -w rexray/cli/service_unix.go
gofmt -w rexray/cli/cli.go
gofmt -w rexray/cli/cmds_service.go
gofmt -w rexray/cli/cmds_device.go
gofmt -w rexray/cli/term/terminal_bsd.go
gofmt -w rexray/cli/term/terminal_linux.go
gofmt -w rexray/cli/term/terminal_notwindows.go
gofmt -w test/test.go
gofmt -w rexray/cli/term/terminal_windows.go
gofmt -w util/util.go
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray.a .
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/core.a ./core
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/core/errors.a ./core/errors
go build  -ldflags "-X github.com/emccode/rexray/core/version.SemVer=0.3.2-rc3+5 -X github.com/emccode/rexray/core/version.Branch=feature/gomk -X github.com/emccode/rexray/core/version.Epoch=1455316971 -X github.com/emccode/rexray/core/version.ShaLong=a1763e8574dfc9f7af4ae4397199238187af93f8 -X github.com/emccode/rexray/core/version.Arch=Darwin-x86_64" -o .gomk/tmp/build/pkg/darwin_amd64/rexray/core/version.a ./core/version
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module.a ./daemon/module
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon.a ./daemon
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module/admin.a ./daemon/module/admin
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module/docker/remotevolumedriver.a ./daemon/module/docker/remotevolumedriver
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/daemon/module/docker/volumedriver.a ./daemon/module/docker/volumedriver
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers.a ./drivers
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/mock.a ./drivers/mock
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/os.a ./drivers/os
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/os/linux.a ./drivers/os/linux
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage.a ./drivers/storage
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/ec2.a ./drivers/storage/ec2
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/gce.a ./drivers/storage/gce
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/isilon.a ./drivers/storage/isilon
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/openstack.a ./drivers/storage/openstack
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/rackspace.a ./drivers/storage/rackspace
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/scaleio.a ./drivers/storage/scaleio
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/virtualbox.a ./drivers/storage/virtualbox
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/vmax.a ./drivers/storage/vmax
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/storage/xtremio.a ./drivers/storage/xtremio
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/volume.a ./drivers/volume
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/drivers/volume/docker.a ./drivers/volume/docker
go build  -ldflags "-X github.com/emccode/rexray/core/version.SemVer=0.3.2-rc3+5 -X github.com/emccode/rexray/core/version.Branch=feature/gomk -X github.com/emccode/rexray/core/version.Epoch=1455316971 -X github.com/emccode/rexray/core/version.ShaLong=a1763e8574dfc9f7af4ae4397199238187af93f8 -X github.com/emccode/rexray/core/version.Arch=Darwin-x86_64" -o .gomk/tmp/build/bin/darwin_amd64/rexray ./rexray
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/rexray/cli.a ./rexray/cli
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/rexray/cli/term.a ./rexray/cli/term
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/test.a ./test
go build  -o .gomk/tmp/build/pkg/darwin_amd64/rexray/util.a ./util
[0]akutz@pax:rexray$ 
```

Here it is printed out:

```
[0]akutz@pax:rexray$ .gomk/tmp/build/bin/darwin_amd64/rexray version
Binary: /Users/akutz/Projects/go/src/github.com/emccode/rexray/.gomk/tmp/build/bin/darwin_amd64/rexray
SemVer: 0.3.2-rc3+5
OsArch: Darwin-x86_64
Branch: feature/gomk
Commit: a1763e8574dfc9f7af4ae4397199238187af93f8
Formed: Fri, 12 Feb 2016 16:42:51 CST
```

**Comment by akutz** [comment]
So aside from RPMs, DEBs, Tarballs, and the deploy section I think we're good. The basic build structure is in place, and I believe it's a good improvement on the existing one. Especially since even builds are cached. Normally Go doesn't cache the results of `go build`. Gomk does. That means building from the CLI to test small changes is *much* faster. Plus, I create binaries of the tests, so we can reuse them later. I am thinking of uploading those to deployments as well so we can test them locally from CI builds. Note in the example below the command `make tests-build` builds the test binaries but does not execute them (`make tests` does). However, we can also execute the test binaries individually if we desire. 

Also note for REX-Ray the top-level test-related goals are `tests`. This is because the top-level `test` directory in the project was conflicting with the top-level goal `test`.

```
[0]akutz@pax:rexray$ make tests-build
go install  ./rexray/cli
go install  ./test
go install  ./util
gofmt -w rexray/cli/cli_test.go
gofmt -w test/test_test.go
gofmt -w test/bad_mock_drivers_test.go
gofmt -w test/volume_driver_test.go
gofmt -w test/os_driver_test.go
gofmt -w test/storage_driver_test.go
gofmt -w util/util_test.go
go test -cover -c ./util -o .gomk/tmp/tests/util/util.test 
go test -cover -c ./test -o .gomk/tmp/tests/test/test.test -coverpkg "github.com/emccode/rexray","github.com/emccode/rexray/core"
go test -cover -c ./rexray/cli -o .gomk/tmp/tests/rexray/cli/cli.test 
[0]akutz@pax:rexray$ .gomk/tmp/tests/test/test.test
INFO[0000] [badMockOSDriver]                            
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [badMockVolumeDriver]                        
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [badMockStorageDriver]                       
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] getting mounts                                deviceName= driverName=mockOSDriver mountPoint=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] checking filesystem mount                     driverName=mockOSDriver mountPoint=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] unmounting filesystem                         driverName=mockOSDriver mountPoint=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] mounting filesystem                           device= driverName=mockOSDriver mountLabel= mountOptions= target=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] formatting if blank or overwriteFs specified  deviceName= driverName=mockOSDriver fsType= overwriteFs=false
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] mockOSDriver                                 
INFO[0000] mockVolumeDriver                             
INFO[0000] mockStorageDriver                            
INFO[0000] []                                           
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] []                                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] []                                           
INFO[0000] mockOSDriver                                 
INFO[0000] mockVolumeDriver                             
INFO[0000] mockStorageDriver                            
INFO[0000] mockOSDriver                                 
INFO[0000] mockVolumeDriver                             
INFO[0000] mockStorageDriver                            
INFO[0000] mockOSDriver                                 
INFO[0000] mockVolumeDriver                             
INFO[0000] mockStorageDriver                            
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] initialized count                             count=0 volumeName=
INFO[0000] set count to                                  count=1 volumeName=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] status of count                               exists=false volumeName=
INFO[0000] initialized count                             count=0 volumeName=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] initialized count                             count=0 volumeName=
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] [mockOSDriver]                               
INFO[0000] [mockVolumeDriver]                           
INFO[0000] [mockStorageDriver]                          
INFO[0000] []                                           
INFO[0000] []                                           
INFO[0000] []                                           
PASS
coverage: 94.2% of statements in github.com/emccode/rexray, github.com/emccode/rexray/core
[0]akutz@pax:rexray$ 
```

**Comment by akutz** [comment]
Closing this as it will be replaced with the v2 of this.

**Pull request closed without merging**
